package UIpkg;
import java.io.*;
import java.net.*;
import com.mysql.jdbc.Connection;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * server.java
 *
 * Created on May 24, 2015, 6:22:45 PM
 */



/**
 *
 * @author Banu Nissanka
 */
public class server extends javax.swing.JFrame {

    int a=0;
    int x=0;
    Connection conn;
 
    String[] crrAns = new String[5]; //array to store correct answers for 5 randomly selected questions
    String[] stdAns = new String[5];//array to store user answers for 5 randomly selected questions

    /** Creates new form server */
    public server() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Server");

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(jButton1)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {

    
try
{
ServerSocket welcomeSocket = new ServerSocket(3012);
while(true) {
//wait for connection
Socket connectionSocket = welcomeSocket.accept();

//get input output streams
BufferedReader inFromClient = new BufferedReader(new InputStreamReader(connectionSocket.getInputStream()));
DataOutputStream outToClient = new DataOutputStream(connectionSocket.getOutputStream());

//**Server receives the student’s answer to the question
stdAns[0] = inFromClient.readLine();
stdAns[1]=inFromClient.readLine();
stdAns[2]=inFromClient.readLine();
stdAns[3]=inFromClient.readLine();
stdAns[4]=inFromClient.readLine();

crrAns[0] = inFromClient.readLine();
crrAns[1] = inFromClient.readLine();
crrAns[2] = inFromClient.readLine();
crrAns[3] = inFromClient.readLine();
crrAns[4] = inFromClient.readLine();


int result = finalMark();
String Result = String.valueOf(result);

outToClient.writeBytes(Result + '\n'); //**server provide the final mark to the client.
}
}
catch(Exception e)
{
}
        // TODO add your handling code here:
    }


//**calculates marks according to the student’s response against the correct answer and returns
    public int finalMark()
    {
   // System.out.println(UserAns[2]);
    int total = 0;
    int b;

    for(b=0;b<5;b++)
    {
        if(crrAns[b].equals(stdAns[b]))
           total++;
     }
    return total;
    }


    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new server().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration

}
